name: ex_bloc
description: ExBloc provide simple way to organize bloc middleware and dispatch events.
version: 0.2.15
# author: Alex Vegner <alexvegner@gmail.com>
repository: https://github.com/AlexVegner/ex_bloc
issue_tracker: https://github.com/AlexVegner/ex_bloc/issues
homepage: https://github.com/AlexVegner/ex_bloc

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  bloc: ^3.0.0
  
dev_dependencies:
  test: ^1.9.4
  # test_coverage: ^0.2.0
  mockito: ^4.0.0
  # effective_dart: ^1.1.1
